### PR TITLE
hints and scores for all players

### PR DESCRIPTION
**Pull request by sausyn**
**hints**: it shows the first letter of the answer. If called several times on the same question it shows one more letter each time.
**scores**: added the ability to show the scores for all players

!hint or !h - take a hint
!scores or !score all - check the score of all players

### CODE REVIEW

**Comment by yincrash** [comment]
Whoops. `!scores` can get disconnected from some services because it is spamming. I'm going to have to remove that for now.

**Comment by bryanwoods** [comment]
@yincrash this is awesome -- any plans to bump the npm version?

**Comment by yincrash** [comment]
hmm yeah, i'll do that now

**Comment by yincrash** [comment]
version bumped. there's also @seangibat's fuzzy matching in this version as well

**Pull request merged**
